version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_cadastrocliente
    environment:
      SA_PASSWORD: "Arquivo13@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - cadastrocliente_net
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: CadastroCliente.API/Dockerfile
    container_name: cadastrocliente_api
    ports:
      - "8000:8000"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - cadastrocliente_net

networks:
  cadastrocliente_net:
    driver: bridge

volumes:
  sql_data:
